2025-04-18 01:02:30,386 INFO    MainThread:1417988 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-04-18 01:02:30,386 INFO    MainThread:1417988 [wandb_setup.py:_flush():67] Configure stats pid to 1417988
2025-04-18 01:02:30,386 INFO    MainThread:1417988 [wandb_setup.py:_flush():67] Loading settings from /speech/shoutrik/.config/wandb/settings
2025-04-18 01:02:30,386 INFO    MainThread:1417988 [wandb_setup.py:_flush():67] Loading settings from /speech/shoutrik/torch_exp/ConvNet/finetune/wandb/settings
2025-04-18 01:02:30,386 INFO    MainThread:1417988 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-04-18 01:02:30,386 INFO    MainThread:1417988 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /speech/shoutrik/torch_exp/ConvNet/finetune/wandb/run-20250418_010230-t38frkp7/logs/debug.log
2025-04-18 01:02:30,387 INFO    MainThread:1417988 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /speech/shoutrik/torch_exp/ConvNet/finetune/wandb/run-20250418_010230-t38frkp7/logs/debug-internal.log
2025-04-18 01:02:30,387 INFO    MainThread:1417988 [wandb_init.py:init():761] calling init triggers
2025-04-18 01:02:30,387 INFO    MainThread:1417988 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'wandb_project': 'ConvNet_expts', 'wandb_entity': 'shoutrik', 'run_name': 'vit_b_32_classifier_finetune', 'train_data_path': '/speech/shoutrik/Database/INaturalist/inaturalist_12K/train', 'valid_data_path': '/speech/shoutrik/Database/INaturalist/inaturalist_12K/valid', 'test_data_path': '/speech/shoutrik/Database/INaturalist/inaturalist_12K/test', 'finetune_strategy': 2, 'input_channels': 3, 'num_channels': [32, 64, 128, 256, 512], 'num_layers': 5, 'kernel_size': [7, 5, 3, 3, 3], 'padding': [0, 0, 0, 0, 0], 'stride': [1, 1, 1, 1, 1], 'maxpool_kernel_size': 2, 'maxpool_padding': 0, 'maxpool_stride': 2, 'feedforward_dim': 512, 'num_classes': 10, 'apply_maxpool': True, 'apply_batchnorm': True, 'input_size': 224, 'dropout_p': 0.3, 'conv_activation_function': 'GELU', 'feedforward_activation_function': 'ReLU', 'num_channels_multiplier': 1.0, 'apply_augmentations': True, 'batch_size': 128, 'num_workers': 16, 'learning_rate': 0.0001, 'weight_decay': 0.0001, 'max_epoch': 10, 'label_smoothing': 0.2, 'seed': 424, 'warmup_steps': 250, '_wandb': {}}
2025-04-18 01:02:30,387 INFO    MainThread:1417988 [wandb_init.py:init():784] starting backend
2025-04-18 01:02:30,387 INFO    MainThread:1417988 [wandb_init.py:init():788] sending inform_init request
2025-04-18 01:02:30,412 INFO    MainThread:1417988 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-18 01:02:30,412 INFO    MainThread:1417988 [wandb_init.py:init():798] backend started and connected
2025-04-18 01:02:30,415 INFO    MainThread:1417988 [wandb_init.py:init():891] updated telemetry
2025-04-18 01:02:30,448 INFO    MainThread:1417988 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-04-18 01:02:30,994 INFO    MainThread:1417988 [wandb_init.py:init():990] starting run threads in backend
2025-04-18 01:02:31,131 INFO    MainThread:1417988 [wandb_run.py:_console_start():2375] atexit reg
2025-04-18 01:02:31,132 INFO    MainThread:1417988 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-04-18 01:02:31,132 INFO    MainThread:1417988 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-04-18 01:02:31,132 INFO    MainThread:1417988 [wandb_run.py:_redirect():2315] Redirects installed.
2025-04-18 01:02:31,134 INFO    MainThread:1417988 [wandb_init.py:init():1032] run started, returning control to user process
2025-04-18 01:03:04,460 INFO    MsgRouterThr:1417988 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-04-18 01:03:04,755 ERROR   MainThread:1417988 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 01:03:04,759 ERROR   MainThread:1417988 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 01:03:04,759 ERROR   MainThread:1417988 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 01:03:04,759 ERROR   MainThread:1417988 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 01:03:04,760 ERROR   MainThread:1417988 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 01:03:04,760 ERROR   MainThread:1417988 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 01:03:04,760 ERROR   MainThread:1417988 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 01:03:04,760 ERROR   MainThread:1417988 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 01:03:04,761 ERROR   MainThread:1417988 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 01:03:04,761 ERROR   MainThread:1417988 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 01:03:04,761 ERROR   MainThread:1417988 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 01:03:04,761 ERROR   MainThread:1417988 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 01:03:04,761 ERROR   MainThread:1417988 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 01:03:04,762 ERROR   MainThread:1417988 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 01:03:04,762 ERROR   MainThread:1417988 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-18 01:03:04,762 ERROR   MainThread:1417988 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/shoutrik/espnet/espnet_feb24_clean/tools/anaconda/envs/espnet_feb24_clean/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
